### ISSUE TITLE
Tutorial: update dead links

### ISSUE THREAD

**Issue by mikaelarguedas** [ros-naoqi/nao_moveit_config#11]
repository links in tutorial are outdated.
Also considering a refactor/homogeneization of the main readme and the tutorial would be great

**Comment by nlyubova** [comment]
done updating the links !
and will do a homogeneization in future ;)

**Comment by mikaelarguedas** [comment]
I posted that issue to remind me to do it at some point. Thanks for taking care of it!
There were a few dead links left, I fixed them in #12
