### ISSUE TITLE
ompl_interface/OMPLPlanner

### ISSUE THREAD

**Issue by kiwiwan** [ros-naoqi/nao_moveit_config#13]
When i run roslaunch nao_moveit_config demo.launch.
I got an error and some warnning:
[ERROR] [1472018747.925655415]: Exception while loading planner 'ompl_interface/OMPLPlanner': Failed to load library /opt/ros/indigo/lib/libmoveit_ompl_planner_plugin.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libompl.so.10: cannot open shared object file: No such file or directory)
Available plugins: ompl_interface/OMPLPlanner
[ WARN] [1472018748.790092851]: MoveGroup running was unable to load ompl_interface/OMPLPlanner
[ WARN] [1472018748.893354258]: Could not identify parent group for end-effector 'head_eef'

what't wrong?I google this issue,but i can't find the solution.

**Comment by nlyubova** [comment]
Hello,
it seems that you are missing libPoco? how did you install your nao_moveit_config? with apt-get or from source?

**Comment by kiwiwan** [comment]
I install nao nao_moveit_config with catkin.
Missing libPoco?What should i do to fix the problem?

**Comment by nlyubova** [comment]
did you install Moveit-full with apt-get? it is the best way to find all dependencies

**Comment by kiwiwan** [comment]
I did.
My system is ubuntu14.04 and ros version is indigo.

**Comment by nlyubova** [comment]
then, you can try to install this package with apt-get to be sure about all dependencies.

**Comment by nlyubova** [comment]
did you source your moveit?

**Comment by kiwiwan** [comment]
I install moveit with apt-get install ros-indigo-moveit-full.
Did not source it.

**Comment by kiwiwan** [comment]
My problem is fixed when i sudo apt-get install ros-indigo-ompl and sudo apt-get update.
But the result is :0 upgraded, 0 newly installed, 0 to remove and 54 not upgraded.
I don't know why it works.Because i run sudo apt-get update before.And it did not worked.

@nlyubova ,Thanks for your reply.
