### ISSUE TITLE
Kinetic release

### ISSUE THREAD

**Issue by nlyubova** [ros-naoqi/nao_moveit_config#15]
Can we release it for Kinetic?

**Comment by nlyubova** [comment]
@mikaelarguedas can we release your package for Kinetic?

**Comment by mikaelarguedas** [comment]
@nlyubova can you confirm that this package is working fine on a real robot for kinetic (with everything from binaries except this package alone in its own workspace) ? I'd like to avoid releasing broken packages like we discovered recently for other packages

**Comment by mikaelarguedas** [comment]
done
