### ISSUE TITLE
Does it work with NAO V5

### ISSUE THREAD

**Issue by adelth** [ros-naoqi/nao_moveit_config#19]
Do the packages also work with Nao v5? 
I have followed the readme and can start rviz. NAO is detected, but not all joints can be moved. For example, the upper arms can be moved, but not the forearms.
Among other things I get the following error messages:
``` sh
[INFO] [1599561175.299288339]: Loading robot model 'NaoH25V50'...
WARN] [1599561175.423406941]: Could not identify parent group for end-effector 'head_eef'.
ERROR] [1599561175.469343825]: Semantic description is not specified for the same robot as the URDF
```

**Comment by adelth** [comment]
To answer the question myself, I just had to rebuild the needed packages (nao_dcm_robot and nao_dcm_driver) myself. Now moveit also works with my NAO V5.

**Comment by ysys98** [comment]
> To answer the question myself, I just had to rebuild the needed packages (nao_dcm_robot and nao_dcm_driver) myself. Now moveit also works with my NAO V5.

HI , how do you rebuild the needed packages (nao_dcm_robot and nao_dcm_driver) myself and what version ROS of yours?
