### ISSUE TITLE
Unable to identify any set of controllers ...

### ISSUE THREAD

**Issue by edgarriba** [ros-naoqi/nao_moveit_config#2]
Error obtained when I try to execute a trajectory in demo.launch

[ERROR] [1413312795.794861666]: Unable to identify any set of controllers that can actuate the specified joints: [ LElbowRoll LElbowYaw LShoulderPitch LShoulderRoll LWristYaw ]
[ERROR] [1413312795.794926198]: Known controllers and their joints:

**Comment by mikaelarguedas** [comment]
That means that the controllers defined in launch/fake_moveit_controller_manager.launch.xml are not recognized by Rviz,  the rosparam has not been set properly
What version are you running 0.0.2-0 or 0.0.3-0 ?

**Comment by edgarriba** [comment]
the version in master branch in simulation mode

**Comment by mikaelarguedas** [comment]
I haven't been able to reproduce the issue. 
I'm using the master version of both nao_moveit_config and nao_robot in a brand new workspace.
Is it the same for you ? 
Does this problem occur only on the group left_arm or is it the same for every planning group ?

**Comment by edgarriba** [comment]
it's the same in all groups. Could this problem be a consequence of nao_dcm crashes ?

**Comment by mikaelarguedas** [comment]
demo. launch is supposed to be runned when dcm is not running so this
shouldn't be the problem.

If dcm or gazebo is running you should run moveit_planner.launch and not
demo.launch.

I'm looking at the DCM issue, I think that you might be missing some naoqi
modules in your /etc/naoqi/autoload.ini file. Can you copy paste the
content of that file as a comment in this issue
https://github.com/ros-aldebaran/nao_dcm_robot/issues/1 ?

2014-10-15 10:16 GMT+02:00 Edgar Riba notifications@github.com:

**Comment by mikaelarguedas** [comment]
@edgarriba Did you succeed to solve your problem at some point ?
Should we keep this issue open ?

**Comment by edgarriba** [comment]
hi @keulYSMB , sorry for the delay. We didn't solve the problem since we were working on ros indigo and we didn't have time to change to hydro.
