### ISSUE TITLE
no interactive markers when using real NAO

### ISSUE THREAD

**Issue by sailsolar** [ros-naoqi/nao_moveit_config#6]
Interactive markers pops up when i run `roslaunch nao_moveit_config demo.launch`.
But, if I use `roslaunch nao_dcm_bringup nao_dcm_H25_bringup_remote.launch` and then 
`roslaunch nao_moveit_config moveit_planner.launch`, after changing the NAO IP in '.yaml' file, no interactive markers are displayed after clicking interact. The only option to interact with NAO is manipulating camera controls. Checking "Allow approximate IK Solutions" doesn't make any difference. 
Please guide me what should I do.

**Comment by mikaelarguedas** [comment]
@nlyubova: can you try this on a real nao? I think that this error appeared in 166c9f3b4d7de0e1ac31d94b5af4d466ae574396 the markers were properly displayed before. I think it comes from the modification of the end effectors.

**Comment by sailsolar** [comment]
@keulYSMB: Sir, what should I do in this regard?

**Comment by nlyubova** [comment]
@keulYSMB ooops really sorry, That's true. Seams that I've broken it ... Will fix it, no worries  :)

**Comment by nlyubova** [comment]
@husnain-ahmad - start MoveIt! with a launch file like demo_real.launch here (the last commit c7c098ef6bfddb0d1de466f330cc05cbf8e9b413 in https://github.com/nlyubova/nao_moveit_config), it works in this case; so there is a marker and it works to both planning and executing actions

**Comment by nlyubova** [comment]
The only problem is that "static_transform_publisher" is missing in moveit_planner.launch

@husnain-ahmad try to add it like this to your moveit_planner.launch file and it should work
    <node pkg="tf" type="static_transform_publisher" name="virtual_joint_broadcaster_0" args="0 0 0 0 0 0 odom base_link 100" />

**Comment by sailsolar** [comment]
@nlyubova: You guys Rock!!
It worked like a charm with the new launch file. Thanks a million for your support.
I have used the `demo_real.launch` file from your updated repository.

**Comment by mikaelarguedas** [comment]
Thanks Natalia,

Glad it's working again.
Happy programming

**Comment by vrabaud** [comment]
This bug has not been fixed yet right ? Waiting for @nlyubova

**Comment by nlyubova** [comment]
Do you want me to add the line with publishing a robot to the launch file?

**Comment by mikaelarguedas** [comment]
The idea would be to track when/where this publisher disappeared given that this bug appeared "recently". And to find the right place to put it to be sure that this will be working for both virtual and real robot without having duplicated publishers

**Comment by nlyubova** [comment]
@keulYSMB it is not a bug. I've removed the publisher from the bringup launch file since it is the only way to make both (the virtual and real robot) published well (without twicely published robot for the virtual one)

**Comment by vrabaud** [comment]
@nlyubova , you have a file that works in your repo, can you please make a PR to share it ? Thx.

**Comment by mikaelarguedas** [comment]
@vrabaud  @nlyubova My bad I was supposed to commit that file 5 days ago... I'll commit it under another name and see if it's still compatible with the gazebo plugin. It seems that it has been tested and validated on real NAO.

**Comment by nlyubova** [comment]
@vrabaud we have already agreed with Mikael and he prefer to change his file.
@keulYSMB  great! just do it :) or I can commit mine

**Comment by mikaelarguedas** [comment]
done in f7607f294ab1093a7f8e62ad3fe08a26c3b718f9. 
Didn't change anything to the original file for now, trying to figure out why it's working on the real nao and not the gazebo one. Will let you know if I find out.

**Comment by nlyubova** [comment]
how can I check with Gazebo? I've checked it once with my current master and it was showing Nao in Gazebo and it was staying and not falling. does it means that it works or not?

**Comment by nlyubova** [comment]
tested with roslaunch nao_gazebo_plugin nao_gazebo_plugin_H25.launch The robot is staying and not falling ! but it slowly moves backwards and continuously moves fingers :) also can data from sensors. But how can I check it together with moveIt? what it suppose to do?

**Comment by nlyubova** [comment]
also can data from sensors. But how can I check it together with moveIt? what it suppose to do?

**Comment by mikaelarguedas** [comment]
ok I renamed the demo_real launchfile into moveit_planner.launch to match the commands in the tutorials. It's now working with gazebo after removing namespace in ros-naoqi/nao_robot@f8eeae0893e15428041c7600cb68588ff85714e1
