### ISSUE TITLE
Homogenize group names

### ISSUE THREAD

**Issue by mikaelarguedas** [ros-naoqi/nao_moveit_config#7]
group names are not on the same format since 166c9f3b4d7de0e1ac31d94b5af4d466ae574396
If the way to name them is: "side_bodyChain" we should rename all groups to match it

**Comment by vrabaud** [comment]
@ nlyubova, that's on your side right ?

**Comment by mikaelarguedas** [comment]
fixed in a06ae42c80e1d96089120f63f9c55a40746f7c2b
